Adicionando posts regressao-linear.md e entendendo-redes-convolucionais.md
ai-girls/dev-to-posts pull request #4
Opened 2020-03-10 01:54 UTC by giselyalves13

adicionando novos posts

## Resumo do seu post

> Insira aqui um resumo do seu post que você acabou de submeter. 

## Observações

* Verifique se você está submentando apenas o arquivo com o seu arquivo.
* Lembre-se, esse arquivo deve ser formado pelo titulo do seu post, exemplo:    
    ```
    introducao-ao-dev-to.md
    ```
* O arquivo deve ser no formato `Markdown`, então ele deverá terminar com `.md`

## Comentários

> Insira aqui alguma dúvida ou comentário que você tenha, a revisora irá responder :)

## Agradecemos por sua publicação e participação!

2020-03-14 15:12 UTC, naanadr commented
Olá Gisely, agradecemos por ter submetido artigos para o nosso blog.

Eu só queria te pedir uma coisinha.

Você poderia adicionar mensagens de commits que conte uma história? Por exemplo `adiciona post blablablabl`. Pois a mensagem de commit está `add files via upload`. Isso vai nós ajudar a entender melhor o histórico de commits no repositório. Seria bom ser dois commits, um para cada post.

2020-03-23 23:15 UTC, giselyalves13 commented
alterado!

2020-03-24 21:52 UTC, naanadr commented
Obrigada.

Caso você queira dar uma olhada melhor em `git reset` para outro momento, segue um link legal:

https://stackoverflow.com/questions/22682870/git-undo-pushed-commits

2020-03-24 22:40 UTC, naanadr requested changes
Acabei fazendo vários comentários e isso foi apenas para um artigo, foi mal T.T

Alguns comentários são mais sugestões e outros são realmente necessários, você pode comentar também o que você acha e tudo mais. Esse é um momento realmente de troca e bater um papo. 

PS: o outro artigo ainda vou revisar. Gostei bastante do conteúdo e obrigada por compartilhar com a gente :)

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +![Rede AlexNet com 8 camadas](https://miro.medium.com/max/2154/1*HMP8TthpVRljInDPoNHS5A.jpeg)
Essa imagem é uma LeNet né? Aqui na descrição ta AlexNet.

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +# Entradas
Um padrão no Markdown é seguir uma hierarquia de cabeçalhos... como lá no começo  tem um `#`, no resto do documento deve ser usado `##` e dentro deles `###`, assim por diante.
```suggestion
## Entradas
```

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +# Convoluções
Mesma coisa aqui:

```suggestion
## Convoluções
```

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +As convoluções funcionam como filtros que enxergam pequenos quadrados e vão “escorregando” por toda a imagem captando os traços mais marcantes. Explicando melhor, com uma imagem 32x32x3 e um filtro q
```suggestion
As convoluções funcionam como filtros que enxergam pequenos quadrados e vão “escorregando” por toda a imagem captando os traços mais marcantes. Explicando melhor: com uma imagem 32x32x3 e um filtro que cobre uma área de 5x5 da imagem com movimento de 2 saltos (chamado de stride), o filtro passará pela imagem inteira, por cada um dos canais, formando no final um feature map ou activation map de 28x28x1.
```

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +As convoluções funcionam como filtros que enxergam pequenos quadrados e vão “escorregando” por toda a imagem captando os traços mais marcantes. Explicando melhor, com uma imagem 32x32x3 e um filtro q
Será que não seria melhor fazer um subtópico para falar melhor sobre janela deslizante? E no final acho que ficou muita coisa nova "jogada", por exemplo, uma pessoa leiga (que deve ser o público alvo desse post né?) não vai entender muito bem o que é um `feature map` e `activation map`. O que tu acha?

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +<small> *Entrada de 28x28 dimensões com receptive field de área 5x5.* </small>
Mesma coisa aqui... o que seria um `receptive field`?

Se o texto ficar muito grande, você pode explicar só por cima mesmo, ou talvez depois fazer um outro post.

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +# Função de ativação
```suggestion
## Função de ativação
```

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +As funções de ativação servem para trazer a não-linearidades ao sistema, para que a rede consiga aprender qualquer tipo de funcionalidade. Há muitas funções, como  [sigmoid](https://en.wikipedia.org/
```suggestion
As funções de ativação servem para trazer a não-linearidades ao sistema, para que a rede consiga aprender qualquer tipo de funcionalidade. Há muitas funções, como  [sigmoid](https://en.wikipedia.org/wiki/Sigmoid_function),  [tanh](https://pt.wikipedia.org/wiki/Tangente_hiperb%C3%B3lica)  e  [softmax](https://pt.wikipedia.org/wiki/Fun%C3%A7%C3%A3o_log%C3%ADstica), mas a mais indicada para redes convolucionais é a  [Relu](https://en.wikipedia.org/wiki/Rectifier_(neural_networks))  por ser mais eficiente computacionalmente sem grandes diferenças de acurácia quando comparada a outras funções. Essa função zera todos os valores negativos que estão na saída da camada anterior.
```

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +Uma camada de pooling serve para simplificar a informação da camada anterior. Assim como na convolução, é escolhida uma unidade de área, por exemplo 2x2, para transitar por toda a saída da camada ant
```suggestion
Uma camada de pooling serve para simplificar a informação da camada anterior. Assim como na convolução, é escolhida um tamanho de janela, por exemplo 2x2, para transitar por toda a saída da camada anterior.  Esse tamanho é responsável por reduzir a complexidade da informação que será lida na próxima camada, por exemplo, se a saída da camada anterior for 24x24, a saída do pooling será 12x12.  Para realizar essa redução, é preciso escolher uma função, entre as mais utilizadas está o maxpooling, no qual apenas o maior número dentro dessa região (2x) é passado para a saída. Essa sumarização de informação serve para diminuir a quantidade de pesos a serem aprendidos e também para evitar overfitting.
```

O que você acha? Seria uma sugestão, porque achei esse paragrafo um pouco confuso.

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +Ao final da rede é colocada uma camada Fully connected, onde sua entrada é a saída da camada anterior e sua saída são  _N_  neurônios, com  _N_  sendo a quantidade de classes do seu modelo para final
```suggestion
Ao final da rede é colocada uma camada `Fully Connected (FC)`, onde sua entrada é a saída da camada anterior e sua saída são  _N_  neurônios, com  _N_  sendo a quantidade de classes do seu modelo para finalizar a classificação.
```

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +Abaixo apresento um código simples de exemplo para a construção de um modelo usando CNNs. No código utilizo o  [Tensorflow](https://www.tensorflow.org/), um framework de machine learning, com o  [Ker
Acho que valia a pena colocar o link da base, para as pessoas poderem ver como ela é.

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +# Na Prática!
```suggestion
## Na Prática!
```

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +# Loading the CIFAR-10 datasets
```suggestion
### Carrega a base CIFAR-10 
```

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +# Printing some images
```suggestion
### Mostra algumas imagens
```

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +# Convert labels to categorical
```suggestion
### Converte as labels para o tipo `categorical`  
```

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +Este modelo conta com cinco camadas de convoluções e duas camadas de rede fully connected. O otimizador utilizado é o Stochastic Gradient Descent (SGD) com learning rate de 0.01.
Tu poderia colocar um link sobre o que o SGD que nem tu fez lá em cima com as funções de ativação. O que tu acha?

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +Este modelo conta com cinco camadas de convoluções e duas camadas de rede fully connected. O otimizador utilizado é o Stochastic Gradient Descent (SGD) com learning rate de 0.01.
Por sinal, acho que talvez até colocar o link da documentação do Keras seria legal tbm, pq ajuda as pessoas a entenderem o que é as funções e como usar. A documentação do Keras é bem explicadinha.

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +Deixo aqui alguns links de referências usados por mim para escrever este artigo, de onde também peguei algumas imagens. Recomendo a leitura de todos (;
Ai que massa, adorei \o/

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +  model.add(Conv2D(filters=128, kernel_size=(3, 3), input_shape=(height, width, 3), strides=1, padding='same', activation='relu'))
```suggestion
  model.add(Conv2D(filters=128, kernel_size=(3, 3),
                   input_shape=(height, width, 3),
                   strides=1, padding='same',
                   activation='relu'))  
```

Ajuda na leitura, porque estava muito grande essa linha.

2020-03-24 22:40 UTC, naanadr commented on posts/entendendo-redes-convolucionais.md
> +  model.add(Conv2D(filters=128, kernel_size=(3, 3), input_shape=(height, width, 3), strides=1, padding='same', activation='relu'))
Tem outras linhas meio grandes aqui em baixo também.

2020-03-31 01:38 UTC, naanadr requested changes

2020-03-31 01:38 UTC, naanadr commented on posts/regressao-linear.md
> +Quando ouvimos falar de modelos regressivos, em geral, estamos falando de variáveis dependentes quantitativas. Mas isso não é regra existem regressões para variáveis dependentes qualitativas, como a
```suggestion
Quando ouvimos falar de modelos regressivos, em geral, estamos falando de **variáveis dependentes quantitativas**. Mas isso não é regra existem regressões para **variáveis dependentes qualitativas**, como a Regressão Logística.
```

2020-03-31 01:38 UTC, naanadr commented on posts/regressao-linear.md
> +Esses dados se dividem em variável dependente, que é a variável que vamos predizer, é a nossa resposta, e uma ou mais variáveis independentes que são as que vamos utilizar para entender a relação e c
```suggestion
Esses dados se dividem em **variável dependente**, que é a variável que vamos predizer, é a nossa resposta, e uma ou mais **variáveis independentes** que são as que vamos utilizar para entender a relação e conseguir os resultados.
```

2020-03-31 01:38 UTC, naanadr commented on posts/regressao-linear.md
> +Apesar de nesse artigo eu descrever apenas regressões lineares (“retas”) existem regressões para descrever relações não-lineares também.
Quer colocar algumas referências, para pessoas curiosas darem uma olhada tbm?

2020-03-31 01:38 UTC, naanadr commented on posts/regressao-linear.md
> +# **O que uma regressão pode nos dizer?**
```suggestion
## **O que uma regressão pode nos dizer?**
```

2020-03-31 01:38 UTC, naanadr commented on posts/regressao-linear.md
> +Além disso tudo as regressões são modelos explicáveis, ou seja, não são uma caixa-preta que ninguém entende o porquê daquela resposta e dependendo do assunto essa explicabilidade é mais importante do
```suggestion
Além disso tudo as regressões são modelos explicáveis, ou seja, não são uma caixa-preta que ninguém entende o porquê daquela resposta! Dependendo do assunto essa explicabilidade é mais importante do que uma boa acurácia nas predições.
```

2020-03-31 01:38 UTC, naanadr commented on posts/regressao-linear.md
> +# Regressão Linear Simples
```suggestion
## Regressão Linear Simples
```

2020-03-31 01:38 UTC, naanadr commented on posts/regressao-linear.md
> +# Regressão Linear Múltipla
```suggestion
## Regressão Linear Múltipla
```

2020-03-31 01:38 UTC, naanadr commented on posts/regressao-linear.md
> +Existem algumas formas diferentes de calcular o erro final do modelo para que ele não fique enviesado e que seja possível medir a qualidade do nosso modelo, entretanto vou explicar uma das mais simpl
```suggestion
Existem algumas formas diferentes de calcular o erro final do modelo para que ele não fique enviesado e que seja possível medir a qualidade do nosso modelo, entretanto vou explicar uma das mais simples aqui chamada de **Média dos Erros ao Quadrado (MSE)** que é a soma dos resíduos ao quadrado. Ou seja, para cada resíduo de cada ponto iremos colocá-lo ao quadrado e somar todos eles, dividido pelo número de observações. Portanto, esse modelo vai procurar pela reta que possui o menor MSE e declará-la como a que melhor descreve essas relações.
```

2020-03-31 01:38 UTC, naanadr commented on posts/regressao-linear.md
> +# Referências
```suggestion
## Referências
```

2020-04-02 19:45 UTC, lauraDamacenoAlmeida requested changes

2020-04-02 19:45 UTC, lauraDamacenoAlmeida commented on posts/entendendo-redes-convolucionais.md
> +<small> *Arquitetura da rede LeNet5* </small>
Acho que seria legal colocar um tópico para explicar o que seria CNN, que é um tipo de algoritmo de Deep learning e etc..

2020-04-02 19:45 UTC, lauraDamacenoAlmeida commented on posts/regressao-linear.md
> +![Reta de regressão linear simples](https://thepracticaldev.s3.amazonaws.com/i/vw1t7txehpxxeswu6gmy.png) <small> *Reta de regressão linear simples* <small>
Acho legal diminuir o tamanho da imagem, para isso tente utilizar tags HTML <img src ="https://thepracticaldev.s3.amazonaws.com/i/vw1t7txehpxxeswu6gmy.png" width=? >
Ajusta no width e height da imagem

2020-04-02 19:45 UTC, lauraDamacenoAlmeida commented on posts/regressao-linear.md
> +Apesar de nesse artigo eu descrever apenas regressões lineares (“retas”) existem regressões para descrever relações não-lineares também.
```suggestion
Apesar de que neste artigo eu vou descrever apenas regressões lineares (“retas”) existem regressões para descrever relações não-lineares também.
```

2020-04-02 19:45 UTC, lauraDamacenoAlmeida commented on posts/regressao-linear.md
> +-   Qual delas contribui mais para variável resposta?
```suggestion
-   Qual delas contribui mais para a variável resposta?
```

2020-04-02 19:45 UTC, lauraDamacenoAlmeida commented on posts/regressao-linear.md
> +Lembrem que a regressão quer encontrar melhor reta que descreve a relação entre os dados e para isso é preciso entrar os melhores α e β.
```suggestion
Lembre-se que a regressão quer encontrar melhor reta que descreve a relação entre os dados e para isso é preciso entrar os melhores valores de α e β.
```

2020-04-02 19:45 UTC, lauraDamacenoAlmeida commented on posts/regressao-linear.md
> +Bom, agora a gente já entendeu como funciona uma regressão, mas ainda não sabemos como responder todas aquelas perguntas do começo do artigo. A maioria delas pode ser respondida olhando para os coefi
Acho legal trazer as perguntas e dar as respostas.

2020-05-18 22:09 UTC, naanadr commented
Estou fechando o PR, porque não obtive resposta da autora.

2020-05-18 22:09 UTC, closed without merging