A importância de um código de ética na construção de chatbots e inteligência artificial
ai-girls/dev-to-posts pull request #5
Opened 2020-03-30 20:05 UTC by lauraDamacenoAlmeida

## Resumo do seu post

> Insira aqui um resumo do seu post que você acabou de submeter. 

## Observações

* Verifique se você está submentando apenas o arquivo com o seu arquivo.
* Lembre-se, esse arquivo deve ser formado pelo titulo do seu post, exemplo:    
    ```
    introducao-ao-dev-to.md
    ```
* O arquivo deve ser no formato `Markdown`, então ele deverá terminar com `.md`

## Comentários

> Insira aqui alguma dúvida ou comentário que você tenha, a revisora irá responder :)

## Agradecemos por sua publicação e participação!

2020-03-31 00:33 UTC, naanadr commented
Obrigada por submeter ao repositório da comunidade :heart: 
Vou iniciar a avaliação agora.

2020-03-31 01:26 UTC, naanadr requested changes
Lembrando que alguns comentários são sugestões.

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +#chatbot, #ArtificialIntelligence, #ethic
Aqui pode ser sem o `#`
```suggestion
chatbot, ArtificialIntelligence, ethic 
```

funciona assim no dev.to né? (sinceramente não sei, da ultima vez fiquei uma eternidade tentando colocar as tags).

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +# A importância de um código de ética na construção de chatbots e IA
```suggestion
# A importância de um código de ética na construção de chatbots e em IA
```
O que tu acha?

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +<img src="https://github.com/lauraDamacenoAlmeida/dev-to-posts/blob/master/posts/Captura%20de%20Tela%202020-03-30%20a%CC%80s%2015.58.51.png?raw=true">
```suggestion
<img src="https://github.com/lauraDamacenoAlmeida/dev-to-posts/blob/master/posts/Captura%20de%20Tela%202020-03-30%20a%CC%80s%2015.58.51.png?raw=true">
```
Um comentário sobre esse path... a imagem que aparece no Markdown está vindo desse caminho ai, no caso, ele está vindo do seu projeto. Se você apagar esse projeto ou mudar o nome do arquivo, a imagem vai deixar de aparecer pra gente.

O que eu recomendo fazer, que seria uma opção (se tiver outra pode dizer). Renomear a imagem que você subiu, com um nome mais curto e sem espaços (`imagem-blabla.png`) e colocar essa imagem em uma diretório `posts/anexos/`. Além disso, seria preciso renomear esse path, para passar o caminho que a imagem estará nesse projeto (quando o PR for aceito).

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Ao longo dos últimos anos, muitos investigadores, ativista expuseram os inúmeros erros, preconceitos e uso indevido da tecnologia, como por exemplo o reconhecimento facial utilizado pelas autoridades
```suggestion
Ao longo dos últimos anos, muitos ativista expuseram os inúmeros erros, preconceitos e uso indevido da tecnologia. Como por exemplo o reconhecimento facial utilizado pelas autoridades de Nova York que já penalizou inúmeras pessoas indevidamente, rotulando as pessoas como criminosas ou não.
```
teria links para colocar de referência? Seria legal para as pessoas verem a noticia (tem gente que acha que isso não acontece).

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Dois pesquisadores da Universidade de Stanford treinaram um algoritmo de IA para adivinhar as orientações sexuais das pessoas com base em fotografias. Eles descobriram que era mais preciso do que os
```suggestion
Outro caso, curioso foi o de dois pesquisadores da Universidade de Stanford que treinaram um algoritmo de IA para adivinhar as orientações sexuais das pessoas com base em fotografias. Eles descobriram que era mais preciso do que os humanos que tentaram a tarefa. Os cientistas dizem que seu objetivo era provar que era possível criar tal algoritmo. Porém .... (adicionar o paragrafo abaixo)
```
Mesma coisa aqui, seria legal o link de referência.

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Se os consumidores acessarem alguma vez, alguns podem visar pessoas em suas comunidades e atormentá-las com insultos homofóbicos, nunca considerando a validade dos dados usados para criar a tecnologi
```suggestion
Se os usuários desse sistema acessarem alguma vez,  e forem mal intencionados, eles podem visar pessoas em suas comunidades e atormentá-las com insultos homofóbicos. Sendo assim, os autores do projeto não consideraram a validade dos dados usados para criar a tecnologia.
```
Essa ultima frase eu alterei, mas sinceramente, não sei direito o que ela estava querendo passar.

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Ou, se os policiais usassem algo semelhante para procurar criminosos, os algoritmos tendenciosos poderiam tornar as pessoas de certos grupos étnicos cada vez mais vulneráveis a crimes que eles não co
```suggestion
O mesmo acontece no primeiro exemplo trazido, se os policiais usassem algo semelhante para procurar criminosos? Os algoritmos tendenciosos poderiam tornar as pessoas de certos grupos étnicos cada vez mais vulneráveis a crimes que eles não cometeram.
```

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Os esforços para se lidar com estes desafios crescentes concentram-se frequentemente na importância do binômio “Ética+ IA”.
```suggestion
Os esforços para se lidar com estes desafios crescentes concentram-se frequentemente na importância do binômio **“Ética+ IA”**.
```

Só pra dar mais enfase.

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Existem 3 tipos de aprendizado de máquina Supervisionado, não supervisionado e por reforço. Neste blog como estamos falando mais sobre chatbots vamos falar sobre o supervisionado e não supervisionado
```suggestion
Existem 3 tipos de aprendizado de máquina **supervisionado**, **não supervisionado** e **por reforço**. Neste post como estamos falando mais sobre chatbots vamos falar sobre o **supervisionado** e **não supervisionado**.
```

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Supervisionado: Nós desenvolvedores temos controle sobre o que o bot diz, criando respostas em vez de permitir que os usuários o ensinem, ou seja nós temos um poder maior sobre o que nosso bot vai ap
```suggestion
* Supervisionado: Nós desenvolvedores temos controle sobre o que o bot diz, criando respostas em vez de permitir que os usuários o ensinem, ou seja, nós temos um poder maior sobre o que nosso bot vai "aprender".
```

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +•	Vantagens: Você sabe exatamente como ele vai responder e o bot não pode ser corrompido, a menos que você treine ele com dados corrompidos.
```suggestion
     * Vantagens: Você sabe exatamente como ele vai responder e o bot não pode ser corrompido, a menos que você treine ele com dados corrompidos.
```

Mesma correção para os pontinhos pretos a baixo.

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Aprendizado não supervisionado: O bot é educado por seus usuários e não pelo desenvolvedor.
```suggestion
* Aprendizado não supervisionado: O bot é educado por seus usuários e não pelo desenvolvedor.
```

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +•	Desvantagens: O seu bot vai desenvolver uma personalidade inconsistente e você pode não ter conhecimento do que está sendo ensinado. Na pior das hipóteses, ele se transforma em um software desagrad
Eu ia falar pra por o link do bot racista da microsoft kkkk mas ta la em baixo.

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Se você quiser saber mais a fundo sobre esses tipos de aprendizados, [clique aqui.]( https://dev.to/aigirlsbr/afinal-o-que-e-machine-learning-ih5)
HUHUHUHUHU!!!

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +<img src="https://github.com/lauraDamacenoAlmeida/dev-to-posts/blob/master/posts/Captura%20de%20Tela%202020-03-30%20a%CC%80s%2015.58.36.png?raw=true">
Mesmo comentário sobre a imagem lá de cima.

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +<img src="https://github.com/lauraDamacenoAlmeida/dev-to-posts/blob/master/posts/Captura%20de%20Tela%202020-03-30%20a%CC%80s%2015.58.36.png?raw=true">
Uma coisa que eu esqueci... essas imagens estão na internet não? Porque pode passar a url delas também.

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +A Tay foi um chatbot criado pela Microsoft em março de 2016, onde ela interagia e aprendia com os tweets dos usuários na rede social. E sem o tratamento correto na base de aprendizado, ela acabou em
Coloca alguns links de notícias. 
é bom ter referências.

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +E isso fez com que muitos desenvolvedores e empresas questionassem o aprendizado 100% não supervisionado, e como alternativa o aprendizado semi-supervisionado, onde teríamos um tratamento prévio dos
```suggestion
E isso fez com que muitos desenvolvedores e empresas questionassem o aprendizado 100% não supervisionado. Surgindo como alternativa o aprendizado semi-supervisionado, onde teríamos um tratamento prévio dos dados que serão aprendidos pelo bot. Por exemplo no caso da Tay seria introduzido uma etapa de, identificar palavrões, palavras homofóbicas, racistas, às retirando da base de conhecimento.
```

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +•	Prevenção
Coloca o * no lugar dessas bolinhas.

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Muitas empresas não pensam em prevenção de abusos por parte dos usuários para o chatbot, por exemplo: reconhecer palavrões, ameaças de morte ou até racismo.
Um comentário também para os parágrafos a baixo... acho que dava pra juntar esses três mini parágrafos de uma linha, em um paragrafo só.

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Algumas bibliotecas de lista negra de código aberto são mantidas e são usadas por agentes de conversação virtual para evitar determinados diálogos, um exemplo disso é o [Wordfilter]( http://tinysubve
```suggestion
Algumas bibliotecas de lista negra de código aberto são mantidas e usadas por agentes de conversação virtual para evitar determinados diálogos, um exemplo disso é o [Wordfilter]( http://tinysubversions.com/2013/09/new-npm-package-for-bot-makers-wordfilter/).
```

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +É mais provável que os usuários confiem em uma empresa transparente e próxima sobre o uso de tecnologia, e um bot é mais provável de ser confiável se os usuários entenderem que o bot está trabalhando
```suggestion
É mais provável que os usuários confiem em uma empresa transparente sobre o uso de tecnologia. Um bot é mais provável de ser confiável se os usuários entenderem que o bot está trabalhando para servir suas necessidades, além de, deixar claro sobre suas limitações.
```
O ajuste dessa ultima linha, não sei se está passando o que você queria passar com a ultima frase.

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Uma vez que os designers podem dotar seus bots com “personalidade” e capacidades de linguagem natural, é importante transmitir aos usuários que eles não estão interagindo com outra pessoa e sim com u
Pode por links?

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +A possibilidade de sistemas baseados em IA perpetuarem preconceitos sociais existentes ou introduzirem novos vieses, é uma das principais preocupações identificadas pela comunidade de IA relacionada
```suggestion
A possibilidade de sistemas baseados em IA perpetuarem preconceitos sociais existentes ou introduzirem novos vieses, é uma das principais preocupações identificadas pela comunidade de IA relacionada à rápida implantação dela.
```

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Preste atenção na base de dados que está sendo utilizada no treinamento da IA ou do chatbot para verificar se ela não está enviesada.
```suggestion
As equipes de desenvolvimento devem estar comprometidas em garantir que seus bots tratem todas as pessoas de forma justa. Isso será alcançado com diversidade em sua equipe de desenvolvimento. Pois empregando uma equipe diversificada focada no design, no desenvolvimento e no teste da tecnologia, o bot terá mais chances de funcionar de forma justa.
Preste atenção na base de dados que está sendo utilizada no treinamento da IA ou do chatbot para verificar se ela não está enviesada.
```

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +E aí vem um questionamento: “Temos uma IA está sendo utilizada para prevenir suicídios, mas até que ponto ela pode interferir nas decisões humanas?”
```suggestion
Informe ao usuário que os dados serão coletados e como serão usados. Não esqueça de obter consentimento do usuário e não colete mais dados pessoais do que o necessário!
E aí vem um questionamento: “Temos uma IA que está sendo utilizada para prevenir suicídios, mas até que ponto ela pode interferir nas decisões humanas?”
```
Um questionamento massa, ele será debatido na palestra? Seria massa que ele não fosse apenas levantado aqui, mas que acontecesse em algum lugar :)

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +É importante sempre pedir feedback aos usuários referente as interações que ele teve, pois isso nos ajuda a entender melhor onde nosso bot está errando e ajusta-lo.
```suggestion
O desempenho dos sistemas baseados em IA podem variar desde o desenvolvimento até a implementação, além, do tempo que o bot é lançado para novos usuários e em novos contextos, é importante continuamente monitorar a confiabilidade. 
Como fazer isso?! Seja transparente sobre a confiabilidade do bot, apresente resumos de desempenho do sistema ou de em um contexto específico. É importante sempre pedir feedbacks aos usuários referente as interações que ele teve, pois isso nos ajudará a entender melhor onde nosso bot está errando e ajustá-lo.
```

2020-03-31 01:26 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +
Oxe kkkk ficou um monte de linha em branco

2020-03-31 01:29 UTC, naanadr commented
> Inserção do meu artigo sobre "A importância de um código de ética na construção de chatbots e inteligência artificial", eu tive que inserir 2 imagens no repositório também, pois elas estavam na minha máquina.
> Agradeço a oportunidade =)

Tu apagou o template do PR que estava aqui kkkkk e esquecesse de por um resumo do teu post. A gente usa o resumo pra fazer a postagem, né?

2020-03-31 02:55 UTC, lauraDamacenoAlmeida commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +#chatbot, #ArtificialIntelligence, #ethic
boa, é sem #

2020-03-31 12:16 UTC, lauraDamacenoAlmeida commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Ao longo dos últimos anos, muitos investigadores, ativista expuseram os inúmeros erros, preconceitos e uso indevido da tecnologia, como por exemplo o reconhecimento facial utilizado pelas autoridades
Coloquei o link

2020-03-31 12:16 UTC, lauraDamacenoAlmeida commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Ao longo dos últimos anos, muitos investigadores, ativista expuseram os inúmeros erros, preconceitos e uso indevido da tecnologia, como por exemplo o reconhecimento facial utilizado pelas autoridades
E eu reescrevi o parágrafo

2020-03-31 12:17 UTC, lauraDamacenoAlmeida commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +E aí vem um questionamento: “Temos uma IA está sendo utilizada para prevenir suicídios, mas até que ponto ela pode interferir nas decisões humanas?”
Então eu ia comentar sobre ele, mas o texto ia ficar maior. A gente pode no futuro fazer um texto sobre isso, oq acha?

2020-04-01 20:00 UTC, lauraDamacenoAlmeida commented
Fiz as alterações conforme solicitado =)

2020-04-01 20:46 UTC, naanadr requested changes

2020-04-01 20:46 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Ao longo dos últimos anos, muitos investigadores, ativista expuseram os inúmeros erros, preconceitos e uso indevido da tecnologia, como por exemplo um modelo usado em casos criminais norte Americanos
```suggestion
Ao longo dos últimos anos, muitos investigadores, ativista expuseram os inúmeros erros, preconceitos e uso indevido da tecnologia, como por exemplo, um modelo usado em casos criminais Norte Americanos para prever quais criminosos têm maior probabilidade de reincidência e com isso os juízes tomam as decisões baseadas nele. Esse sistema foi chamado de [COMPAS](https://medium.com/thoughts-and-reflections/racial-bias-and-gender-bias-examples-in-ai-systems-7211e4c166a1) e demonstrou carregar viés racial ao fazer as suas classificações, onde a cor da pele da pessoa acabava sendo um fator para ser considerado criminoso de alto risco.
```

2020-04-01 20:46 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Supervisionado: Nós desenvolvedores temos controle sobre o que o bot diz, criando respostas em vez de permitir que os usuários o ensinem, ou seja nós temos um poder maior sobre o que nosso bot vai ap
Faltou por o `*` para criar uma lista. Ou você acha melhor não colocar como uma lista?

2020-04-01 20:46 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +•	Vantagens: Você sabe exatamente como ele vai responder e o bot não pode ser corrompido, a menos que você treine ele com dados corrompidos.
E faltou corrigir essa parte aqui tbm (e as outras partes que essa bolinha preta aparece).

2020-04-01 20:46 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +E isso fez com que muitos desenvolvedores e empresas questionassem o aprendizado 100% não supervisionado, e como alternativa o aprendizado semi-supervisionado, onde teríamos um tratamento prévio dos
O que tu acha dessa sugestão?

2020-04-01 20:46 UTC, naanadr commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +É mais provável que os usuários confiem em uma empresa transparente e próxima sobre o uso de tecnologia, e um bot é mais provável de ser confiável se os usuários entenderem que o bot está trabalhando
E esse comentário, tu concorda com essa alteração?

2020-04-02 19:07 UTC, lauraDamacenoAlmeida reviewed
Atualizei as coisas Fe consegue validar?

2020-04-02 19:07 UTC, lauraDamacenoAlmeida commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +Supervisionado: Nós desenvolvedores temos controle sobre o que o bot diz, criando respostas em vez de permitir que os usuários o ensinem, ou seja nós temos um poder maior sobre o que nosso bot vai ap
acho melhor sem lista, coloquei eles como H4 agora

2020-04-02 19:07 UTC, lauraDamacenoAlmeida commented on posts/A-importancia-de-um-codigo-de-etica-na-construcao-de-chatbots-e-IA.md
> +<img src="https://github.com/lauraDamacenoAlmeida/dev-to-posts/blob/master/posts/Captura%20de%20Tela%202020-03-30%20a%CC%80s%2015.58.36.png?raw=true">
ajustei as imagens

2020-04-02 23:16 UTC, naanadr approved these changes

2020-04-02 23:16 UTC, naanadr commented
Aprovado, partindo para publicação!

2020-04-02 23:16 UTC, merged