Adiciona tutorial com imagens
ai-girls/dev-to-posts pull request #8
Opened 2020-04-01 20:37 UTC by naanadr

Adiciona tutorial com imagens, explicando os tópicos:
- Fork
- Escrevendo um post
- Fazer upload de arquivo
- Editar/Remover arquivo
- Pull Request
- Boas práticas de um commit

2020-04-02 19:29 UTC, lauraDamacenoAlmeida requested changes
Segue algumas opiniões minhas referentes aos seus tutoriais Fe =)

2020-04-02 19:29 UTC, lauraDamacenoAlmeida commented on README.md
> +E depois abrir um Pull Request *(o que é um Pull Request? Veja [o nosso tutorial](tutorial/pull-request.md))* que será análisado. Após um review do conteúdo, ele será aprovado e mergeado nesse reposi
```suggestion
E depois abrir um Pull Request *(o que é um Pull Request? Veja [o nosso tutorial](tutorial/pull-request.md))* que será análisado. Após um review do conteúdo, ele poderá ser aprovado e mergeado nesse repositório e o conteúdo será postado no nosso blog, caso ele não for aprovado, iremos colocar algumas sugestões de alterações no seu Pull Request.
```

2020-04-02 19:29 UTC, lauraDamacenoAlmeida commented on tutorial/escrevendo-post.md
> +O GitHUb te levará para uma nova página (após a etapa anterior), onde você fornecerá o nome do arquivo (**item em destaque 2**) e não se esqueça de colocar `.md` como a extensão dele. Você pode mudar
```suggestion
O Github te levará para uma nova página (após a etapa anterior), onde você fornecerá o nome do arquivo (**item em destaque 2**) e não se esqueça de colocar `.md` como a extensão dele. Você pode mudar do editor de texto, para o preview do seu arquivo no **item em destaque 3**. 
```

2020-04-02 19:29 UTC, lauraDamacenoAlmeida commented on tutorial/fork.md
> +Para forkar um repositório, vamos cliar nesse botão **Fork** em destaque na imagem:
o que acha de colocar entre parênteses, "forkar"

2020-04-02 19:29 UTC, lauraDamacenoAlmeida commented on tutorial/fork.md
> +**Uma observação!** Quando o repositorio `ai-girls/dev-to-posts` receber uma alteração, o seu repositório `seu-nome/dev-to-posts` não será alterado. Eles agora são repositórios paralelos. Para saber
Acho legal colocar que isso é vice e versa, tanto as alterações que elas fizeram não será atualizado no projeto principal

2020-04-02 19:29 UTC, lauraDamacenoAlmeida commented on README.md
> +1. [Fork](tutorial/fork.m)
```suggestion
1. [Fazer fork](tutorial/fork.m)
```

2020-04-02 19:29 UTC, lauraDamacenoAlmeida commented on README.md
> +5. [Pull Request](tutorial/pull-request.md)
```suggestion
5. [Fazer um Pull Request](tutorial/pull-request.md)
```

2020-04-03 20:32 UTC, naanadr commented
Fiz as alterações pedidas :)

2020-04-05 02:25 UTC, lauraDamacenoAlmeida approved these changes

2020-04-05 02:29 UTC, merged