Adicona post alavanque-carreira-com-ciencia-dados.md
ai-girls/dev-to-posts pull request #9
Opened 2020-05-06 19:20 UTC by irisferrarini

## Resumo do seu post

> Neste artigo, comento sobre a importância da "alfabetização em dados ou fluência em dados", para qualquer profissional independentemente de sua área de formação e atuação. Também introduzo a Ciência de Dados e dou dicar para quem quiser iniciar nesta área.

## Observações

* Verifique se você está submentando apenas o arquivo com o seu arquivo.
* Lembre-se, esse arquivo deve ser formado pelo titulo do seu post, exemplo:    
    ```
    introducao-ao-dev-to.md
    ```
* O arquivo deve ser no formato `Markdown`, então ele deverá terminar com `.md`

## Comentários

> Sobre a autora Íris Ferrarini: Sou formada em Jornalismo e atualmente trabalho com Planejamento Estratágico e Inteligência da Dados. Sou curiosa por Ciência de Dados e estudo o tema desde meados de 2018. Lancei recentemente o perfil @com.dados no Instagram, que busca falar de forma simples sobre dados. Caso precise falar comigo, mode me envar mensagem no @com.dados ou no LinkedIn www.linkedin.com/in/irisferrarini ou no whatsapp 41 99602-5231

## Agradecemos por sua publicação e participação!

2020-05-15 13:12 UTC, naanadr commented
Oi Íris, me desculpe a demora para ver o seu PR. A notificação do Github se perdeu na minha caixa de email. Vou dar uma olhadinha nele hoje <3 obrigada por ter submetido.

2020-05-15 14:26 UTC, irisferrarini commented
Tranquilo. Fico à disposição.
Abraço,
Íris

Sent from Yahoo Mail on Android 
 
  On Fri, May 15, 2020 at 10:13, Maria Fernanda<notifications@github.com> wrote:   


Oi Íris, me desculpe a demora para ver o seu PR. A notificação do Github se perdeu na minha caixa de email. Vou dar uma olhadinha nele hoje <3 obrigada por ter submetido.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-05-16 18:56 UTC, naanadr requested changes
O texto está maravilhoso. Obrigada por compartilhar com a gente um pouquinho sua experiência.

2020-05-16 18:56 UTC, naanadr commented on posts/alavanque-carreira-com-ciencia-dados.md
> +Meu primeiro desafio foi liderar um projeto-piloto de análise de dados, por meio do Laboratório Social Good para institutos e fundações empresarias.
Esse laboratório é o mesmo link que está lá em baixo do Radar Social Good

2020-05-16 19:00 UTC, naanadr commented
Oi Íris, só vi agora que você acabou apagando o nosso template. Você pode inserir ele novamente na sua branch? 

Após isso irei aprovar seu PR e publicar o artigo. Obrigada por submeter para a gente : heart:

2020-05-17 23:16 UTC, naanadr commented
Oi @irisferrarini , acho que vc acabou subindo um commit errado. Você adicionou o arquivo e logo depois apagou ele.

Aguardo correções.

2020-05-17 23:18 UTC, naanadr commented
Além disso, o resumo o post será:
(me baseando no seu resumo)
`Íris Ferrarini fala sobre a importância da "alfabetização em dados ou fluência em dados", para qualquer profissional independentemente de sua área de formação e atuação. Nesse artigo ela também inntroduzo a Ciência de Dados e dar algumas dicas de como iniciar na área.`

2020-05-18 21:24 UTC, closed without merging